# Generated by Django 3.1.2 on 2022-03-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Throughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('throughput', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='terminal',
            field=models.CharField(choices=[('Suites', 'Suites'), ('TBIT Main Checkpoint', 'TBIT Main Checkpoint'), ('Terminal 1 - Passenger', 'Terminal 1 - Passenger'), ('Terminal 2 - Passenger', 'Terminal 2 - Passenger'), ('Terminal 3 - Passenger', 'Terminal 3 - Passenger'), ('Terminal 4 - FIS', 'Terminal 4 - FIS'), ('Terminal 4 - Passenger', 'Terminal 4 - Passenger'), ('Terminal 4A - Passenger', 'Terminal 4A - Passenger'), ('Terminal 5 - Passenger', 'Terminal 5 - Passenger'), ('Terminal 5A - Passenger', 'Terminal 5A - Passenger'), ('Terminal 6 - Passenger', 'Terminal 6 - Passenger'), ('Terminal 7 - Passenger', 'Terminal 7 - Passenger')], max_length=23),
        ),
        migrations.CreateModel(
            name='TerminalThroughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('throughput', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='AirportThroughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('throughput', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
            ],
        ),
    ]
