# Generated by Django 3.1.6 on 2022-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0002_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='end',
            field=models.DateField(verbose_name='%-m/%-d/%Y'),
        ),
        migrations.AlterField(
            model_name='search',
            name='start',
            field=models.DateField(verbose_name='%-m/%-d/%Y'),
        ),
    ]
