# Generated by Django 3.1.6 on 2022-04-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0003_auto_20220414_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='start',
            field=models.DateField(),
        ),
    ]
