# Generated by Django 3.1.2 on 2022-04-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0003_auto_20220328_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.terminal')),
            ],
        ),
    ]
